packages:
    - 'local-packages/**'
allowBuilds:
    esbuild: true
    '@parcel/watcher': true
    es5-ext: true
    '@meshtastic/core': true
    '@meshtastic/core@file:local-packages/@meshtastic/core': set this to true or false
