// Hardcoded meshcore command definitions based on https://docs.meshcore.io/cli_commands/
import type { MeshcoreCommand } from '$lib/types';

// All known meshcore commands with their parameters and separators (sorted alphabetically)
export const meshcoreCommandData: MeshcoreCommand[] = [
  { command: 'advert', params: [], separator: null },
  { command: 'advert.zerohop', params: [], separator: null },
  { command: 'board', params: [], separator: null },
  { command: 'clock', params: [], separator: null },
  { command: 'clock sync', params: [], separator: null },
  { command: 'clear stats', params: [], separator: null },
  { command: 'clkreboot', params: [], separator: null },
  { command: 'erase', params: [], separator: null },
  { command: 'get acl', params: [], separator: null },
  { command: 'get adc.multiplier', params: [], separator: null },
  { command: 'get advert.interval', params: [], separator: null },
  { command: 'get af', params: [], separator: null },
  { command: 'get agc.reset.interval', params: [], separator: null },
  { command: 'get allow.read.only', params: [], separator: null },
  { command: 'get bridge.baud', params: [], separator: null },
  { command: 'get bridge.channel', params: [], separator: null },
  { command: 'get bridge.delay', params: [], separator: null },
  { command: 'get bridge.enabled', params: [], separator: null },
  { command: 'get bridge.secret', params: [], separator: null },
  { command: 'get bridge.source', params: [], separator: null },
  { command: 'get bridge.type', params: [], separator: null },
  { command: 'get bootloader.ver', params: [], separator: null },
  { command: 'get direct.txdelay', params: [], separator: null },
  { command: 'get flood.advert.interval', params: [], separator: null },
  { command: 'get flood.max', params: [], separator: null },
  { command: 'get freq', params: [], separator: null },
  { command: 'get guest.password', params: [], separator: null },
  { command: 'get int.thresh', params: [], separator: null },
  { command: 'get lat', params: [], separator: null },
  { command: 'get loop.detect', params: [], separator: null },
  { command: 'get lon', params: [], separator: null },
  { command: 'get multi.acks', params: [], separator: null },
  { command: 'get name', params: [], separator: null },
  { command: 'get owner.info', params: [], separator: null },
  { command: 'get path.hash.mode', params: [], separator: null },
  { command: 'get prv.key', params: [], separator: null },
  { command: 'get public.key', params: [], separator: null },
  { command: 'get pwrmgt.bootmv', params: [], separator: null },
  { command: 'get pwrmgt.bootreason', params: [], separator: null },
  { command: 'get pwrmgt.source', params: [], separator: null },
  { command: 'get pwrmgt.support', params: [], separator: null },
  { command: 'get radio', params: [], separator: null },
  { command: 'get repeat', params: [], separator: null },
  { command: 'get role', params: [], separator: null },
  { command: 'get rxdelay', params: [], separator: null },
  { command: 'get txdelay', params: [], separator: null },
  { command: 'get tx', params: [], separator: null },
  { command: 'gps', params: [{ name: 'state', type: 'enum', options: ['on', 'off'] }], separator: 'space' },
  { command: 'gps advert', params: [{ name: 'policy', type: 'enum', options: ['none', 'share', 'prefs'] }], separator: 'space' },
  { command: 'gps setloc', params: [], separator: null },
  { command: 'gps sync', params: [], separator: null },
  { command: 'log', params: [], separator: null },
  { command: 'log erase', params: [], separator: null },
  { command: 'log start', params: [], separator: null },
  { command: 'log stop', params: [], separator: null },
  { command: 'neighbor.remove', params: [{ name: 'pubkey_prefix', type: 'string' }], separator: 'space' },
  { command: 'neighbors', params: [], separator: null },
  { command: 'password', params: [{ name: 'new_password', type: 'string' }], separator: 'space' },
  { command: 'powersaving', params: [], separator: null },
  { command: 'powersaving off', params: [], separator: null },
  { command: 'powersaving on', params: [], separator: null },
  { command: 'region', params: [], separator: null },
  { command: 'region allowf', params: [{ name: 'freq', type: 'number' }], separator: 'space' },
  { command: 'region denyf', params: [{ name: 'freq', type: 'number' }], separator: 'space' },
  { command: 'region get', params: [{ name: 'name', type: 'string' }], separator: 'space' },
  { command: 'region home', params: [], separator: null },
  { command: 'region list', params: [{ name: 'filter', type: 'string' }], separator: 'space' },
  { command: 'region load', params: [], separator: null, interactive: true },
  { command: 'region put', params: [
    { name: 'name', type: 'string' },
    { name: 'parent_name', type: 'string' }
  ], separator: 'space' },
  { command: 'region remove', params: [{ name: 'name', type: 'string' }], separator: 'space' },
  { command: 'region save', params: [], separator: null },
  { command: 'reboot', params: [], separator: null },
  { command: 'sensor get', params: [{ name: 'key', type: 'string' }], separator: 'space' },
  { command: 'sensor list', params: [{ name: 'start', type: 'number' }], separator: 'space' },
  { command: 'sensor set', params: [
    { name: 'key', type: 'string' },
    { name: 'value', type: 'string' }
  ], separator: 'space' },
  { command: 'set adc.multiplier', params: [{ name: 'value', type: 'number' }], separator: 'space' },
  { command: 'set advert.interval', params: [{ name: 'minutes', type: 'number' }], separator: 'space' },
  { command: 'set af', params: [{ name: 'value', type: 'number' }], separator: 'space' },
  { command: 'set agc.reset.interval', params: [{ name: 'value', type: 'number' }], separator: 'space' },
  { command: 'set allow.read.only', params: [{ name: 'state', type: 'string' }], separator: 'space' },
  { command: 'set bridge.baud', params: [{ name: 'rate', type: 'number' }], separator: 'space' },
  { command: 'set bridge.channel', params: [{ name: 'channel', type: 'string' }], separator: 'space' },
  { command: 'set bridge.delay', params: [{ name: 'ms', type: 'number' }], separator: 'space' },
  { command: 'set bridge.enabled', params: [{ name: 'state', type: 'string' }], separator: 'space' },
  { command: 'set bridge.secret', params: [{ name: 'secret', type: 'string' }], separator: 'space' },
  { command: 'set bridge.source', params: [{ name: 'source', type: 'string' }], separator: 'space' },
  { command: 'set direct.txdelay', params: [{ name: 'value', type: 'number' }], separator: 'space' },
  { command: 'set flood.advert.interval', params: [{ name: 'hours', type: 'number' }], separator: 'space' },
  { command: 'set flood.max', params: [{ name: 'value', type: 'number' }], separator: 'space' },
  { command: 'set freq', params: [{ name: 'frequency', type: 'number' }], separator: 'space' },
  { command: 'set guest.password', params: [{ name: 'password', type: 'string' }], separator: 'space' },
  { command: 'set lat', params: [{ name: 'degrees', type: 'number' }], separator: 'space' },
  { command: 'set loop.detect', params: [{ name: 'state', type: 'string' }], separator: 'space' },
  { command: 'set lon', params: [{ name: 'degrees', type: 'number' }], separator: 'space' },
  { command: 'set multi.acks', params: [{ name: 'state', type: 'string' }], separator: 'space' },
  { command: 'set name', params: [{ name: 'name', type: 'string', maxLength: 32 }], separator: 'space' },
  { command: 'set owner.info', params: [{ name: 'text', type: 'string' }], separator: 'space' },
  { command: 'set path.hash.mode', params: [{ name: 'value', type: 'string' }], separator: 'space' },
  { command: 'set prv.key', params: [{ name: 'private_key', type: 'string' }], separator: 'space' },
  { command: 'set radio', params: [
    { name: 'freq', type: 'number' },
    { name: 'bw', type: 'number' },
    { name: 'sf', type: 'number' },
    { name: 'cr', type: 'number' }
  ], separator: 'comma' },
  { command: 'set repeat', params: [{ name: 'state', type: 'string' }], separator: 'space' },
  { command: 'set rxdelay', params: [{ name: 'value', type: 'number' }], separator: 'space' },
  { command: 'set txdelay', params: [{ name: 'value', type: 'number' }], separator: 'space' },
  { command: 'set tx', params: [{ name: 'dbm', type: 'number' }], separator: 'space' },
  { command: 'setperm', params: [
    { name: 'pubkey', type: 'string' },
    { name: 'permissions', type: 'enum', options: ['0', '1', '2', '3'] }
  ], separator: 'space' },
  { command: 'start ota', params: [], separator: null },
  { command: 'stats-core', params: [], separator: null },
  { command: 'stats-packets', params: [], separator: null },
  { command: 'stats-radio', params: [], separator: null },
  { command: 'tempradio', params: [
    { name: 'freq', type: 'number' },
    { name: 'bw', type: 'number' },
    { name: 'sf', type: 'number' },
    { name: 'cr', type: 'number' },
    { name: 'timeout_mins', type: 'number' }
  ], separator: 'comma' },
  { command: 'time', params: [{ name: 'epoch_seconds', type: 'number' }], separator: 'space' },
  { command: 'ver', params: [], separator: null }
];
